using Avalonia.Controls;
using Avalonia.Data.Converters;
using Avalonia.Markup.Xaml;
using Avalonia.Markup.Xaml.Templates;
using Avalonia.Media;
using Eremex.AvaloniaUI.Controls.DataControl;
using Eremex.AvaloniaUI.Controls.DataGrid;
using Eremex.AvaloniaUI.Controls.Editors;
using System.Globalization;

namespace DemoCenter.Views;

public partial class DataGridColumnBandsView : UserControl
{
    public DataGridColumnBandsView()
    {
        InitializeComponent();
    }

    void DataGridControl_AutoGeneratedColumns(object sender, EventArgs e)
    {
        var dataGrid = (DataGridControl)sender;
        foreach (var column in dataGrid.Columns)
        {
            int separatorIndex = column.FieldName.LastIndexOf("/");
            if (separatorIndex == -1)
            {
                if(column.FieldName == "Total")
                {
                    column.FixedMode = FixedMode.Right;
                    column.CellTemplate = (DataTemplate)Resources["totalTemplate"];
                }
                else
                {
                    column.FixedMode = FixedMode.Left;
                }   
                continue;
            }

            column.BandName = column.FieldName.Substring(0, separatorIndex);
            column.Header = column.FieldName.Substring(separatorIndex + 1);

            if (column.FieldName.Contains("Total"))
            {
                column.CellTemplate = (DataTemplate)Resources["yearTotalTemplate"];
            }
            else
            {
                column.CellTemplate = (DataTemplate)Resources["quarterTemplate"];
            }
            column.EditorProperties = new TextEditorProperties() { DisplayFormatString = "c" };
        }
    }
}

public class ColumnBandsValueToBackgroundConverter : MarkupExtension, IValueConverter
{
    public int MinValue { get; set; }

    public int MaxValue { get; set; }

    public IBrush MinValueBrush { get; set; }

    public IBrush MaxValueBrush { get; set; }

    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is decimal result)
        {
            if (result < MinValue)
                return MinValueBrush;
            else if (result > MaxValue)
                return MaxValueBrush;
        }
        return Brushes.Transparent;
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }

    public override object ProvideValue(IServiceProvider serviceProvider)
    {
        return this;
    }


}